/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ses;

import be.ses.CheckNeighboursInGrid;
import java.util.ArrayList;
import java.util.List;
import java.lang.Integer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    CheckNeighboursInGrid checkNeighboursInGrid = new CheckNeighboursInGrid();


    public void checkNeighboursInGrid(){
        List<Integer> grid = new ArrayList<>();

        grid.addAll(List.of(
        0, 0, 1, 0,
        1, 1, 0, 2,
        2, 0, 1, 3,
        0, 1, 1, 1
        ));
        int width = 4;
        int height = 4;
        int indexToCheck = 5;
        System.out.println(checkNeighboursInGrid.getSameNeighboursIds(grid, width, height, indexToCheck));
    }

    public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    
    // Create an instance of App to call the instance method
    App app = new App();
    app.checkNeighboursInGrid();
}
}
