name: Java CI with Gradle

on:
  push:
    branches:
      - main  # Trigger de pipeline bij pushen naar de main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Gebruik de nieuwste Ubuntu runner

    steps:
    # Stap 1: Check-out de code
    - name: Check out code
      uses: actions/checkout@v2

    # Stap 2: Zet de JDK versie in (bijvoorbeeld JDK 11)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # Specify the distribution here

    # Stap 3: Installeren van Gradle (deze stap is optioneel als je al een Gradle wrapper hebt)
    - name: Set up Gradle
      uses: gradle/wrapper-validation-action@v1

    # Stap 4: Gradle build uitvoeren (dit bouwt je project en voert de tests uit)
    - name: Build with Gradle
      run: ./SES/dependency-management/checkneighbours/gradlew build

    # Stap 5: Voer de tests uit met Gradle
    - name: Run tests with Gradle
      run: ./gradlew test